defaults:
  - global_conf: default
  - data_conf: default
  - model_conf: default
  - train_conf: default
  - _self_

name: ACEquation

data_conf:
  initial_data_n: 200
  boundary_data_n: 200
  pde_data_n: 60000

global_conf:
  seed: 8734

model_conf:
  layer:
    layer_n: 5
    layer_size: [64, 64, 64, 64, 64]

problem_conf:
  dims: 2
  x_range: [-1, 1]
  t_range: [0., 1.]
  initial_cond: cos(pi * x) * (x**2)
  boundary_cond: periodic

train_conf:
  train_t_range: [ 0, 0.5 ]
  eval_t_range: [ 0.5, 0.75 ]
  test_t_range: [ 0.75, 1.0 ]
  pde_sampler: SamplerWithDMIS
  pde_reweighting: BiasedReWeighting
  reweighting_params:
    k_init: 1.5
    k_final: 1.5
    iter_n: ${train_conf.main_conf.max_steps}
  optim_conf:
    lr: 1e-3
  main_conf:
    max_steps: 100000
    pde_batch_size: 20000
    initial_batch_size: 50
    boundary_batch_size: 50
    print_frequency: 1
    model_basic_save_name: ${name}
  sampler_conf:
    forward_batch_size: ${train_conf.main_conf.pde_batch_size}
    mesh_update_thres: 0.4
    addon_points: [ [ 0., -1. ], [ 0., 1. ], [ 0.5, 1. ], [ 0.5, -1. ] ]
    seed_n: 1000
