defaults:
  - global_conf: default
  - data_conf: default
  - model_conf: default
  - train_conf: default
  - _self_

name: Diffusion

global_conf:
  seed: 1024

model_conf:
  layer_n: 2
  layer_size: [16, 16]

problem_conf:
  dims: 2
  x_range: [0, 1.]
  t_range: [0., 1.]
  initial_cond: "2 * sin(pi * x) + 2 * (x - x**3)"
  boundary_cond: "0 * x"

train_conf:
  train_t_range: [ 0, 0.5 ]
  eval_t_range: [ 0.5, 0.75 ]
  test_t_range: [ 0.75, 1.0 ]
  pde_sampler: SamplerWithDMIS
  pde_reweighting: BiasedReWeighting
  reweighting_params:
    k_init: 2
    k_final: 2
    iter_n: ${train_conf.main_conf.max_steps}
  optim_conf:
    lr: 2e-3
  main_conf:
    max_steps: 4000
    pde_batch_size: 20000
    initial_batch_size: 50
    boundary_batch_size: 50
    print_frequency: 1
    model_basic_save_name: ${name}
  sampler_conf:
    forward_batch_size: ${train_conf.main_conf.pde_batch_size}
    mesh_update_thres: 0.4
    addon_points: [[0., 1.], [0., 0.], [0.5, 0.], [0.5, 1.]]
    seed_n: 1000

plot_conf:
  device: cuda
  cut_indxs: [10, 350, 500]
  pinn_path: outputs\compares\Diffusion\Uniform\9\Diffusion_3000.pth
  pinn_s_path: outputs\compares\Diffusion\Interpolation\9\Diffusion_1000.pth
